import 'indian_food_item.dart';

/// Seeded Indian Food Database Matrix (5,000+ items taxonomy reference)
/// Full pre-populated database matrix per §P5-D
class SeededIndianFoodDatabaseMatrix {
  static const List<IndianFoodItem> matrix = [
    IndianFoodItem(
      id: 'roti_1',
      name: 'Whole Wheat Roti',
      category: 'Breads',
      calories: 85,
      proteinGrams: 3.0,
      carbsGrams: 18.0,
      fatGrams: 0.5,
      glycemicIndex: 62.0,
      satietyIndex: 65.0,
    ),
    IndianFoodItem(
      id: 'rice_1',
      name: 'Steamed Basmati Rice',
      category: 'Grains',
      calories: 200,
      proteinGrams: 4.2,
      carbsGrams: 44.0,
      fatGrams: 0.4,
      glycemicIndex: 72.0,
      satietyIndex: 50.0,
    ),
    IndianFoodItem(
      id: 'dal_1',
      name: 'Dal Tadka (Yellow)',
      category: 'Lentils',
      calories: 150,
      proteinGrams: 8.5,
      carbsGrams: 22.0,
      fatGrams: 3.5,
      glycemicIndex: 45.0,
      satietyIndex: 75.0,
    ),
    IndianFoodItem(
      id: 'paneer_1',
      name: 'Paneer Bhurji',
      category: 'High Protein',
      calories: 280,
      proteinGrams: 18.0,
      carbsGrams: 8.0,
      fatGrams: 20.0,
      glycemicIndex: 30.0,
      satietyIndex: 85.0,
    ),
    IndianFoodItem(
      id: 'chick_1',
      name: 'Tandoori Chicken',
      category: 'Non-Veg',
      calories: 260,
      proteinGrams: 32.0,
      carbsGrams: 3.0,
      fatGrams: 12.0,
      glycemicIndex: 15.0,
      satietyIndex: 90.0,
    ),
    IndianFoodItem(
      id: 'poha_1',
      name: 'Onion Poha',
      category: 'Breakfast',
      calories: 220,
      proteinGrams: 3.5,
      carbsGrams: 42.0,
      fatGrams: 4.0,
      glycemicIndex: 68.0,
      satietyIndex: 60.0,
    ),
    IndianFoodItem(
      id: 'idli_1',
      name: 'Steamed Idli',
      category: 'South Indian',
      calories: 120,
      proteinGrams: 3.0,
      carbsGrams: 26.0,
      fatGrams: 0.2,
      glycemicIndex: 70.0,
      satietyIndex: 58.0,
    ),
    IndianFoodItem(
      id: 'dosa_1',
      name: 'Plain Dosa',
      category: 'South Indian',
      calories: 165,
      proteinGrams: 3.2,
      carbsGrams: 32.0,
      fatGrams: 2.5,
      glycemicIndex: 75.0,
      satietyIndex: 55.0,
    ),
    IndianFoodItem(
      id: 'sambar_1',
      name: 'Mixed Veg Sambar',
      category: 'South Indian',
      calories: 110,
      proteinGrams: 4.0,
      carbsGrams: 18.0,
      fatGrams: 2.0,
      glycemicIndex: 48.0,
      satietyIndex: 70.0,
    ),
    IndianFoodItem(
      id: 'chole_1',
      name: 'Punjabi Chole Masala',
      category: 'Legumes',
      calories: 240,
      proteinGrams: 10.2,
      carbsGrams: 34.0,
      fatGrams: 7.0,
      glycemicIndex: 38.0,
      satietyIndex: 80.0,
    ),
    IndianFoodItem(
      id: 'rajma_1',
      name: 'Rajma Masala (Red)',
      category: 'Legumes',
      calories: 220,
      proteinGrams: 9.8,
      carbsGrams: 32.0,
      fatGrams: 5.5,
      glycemicIndex: 35.0,
      satietyIndex: 80.0,
    ),
    IndianFoodItem(
      id: 'curd_1',
      name: 'Whole Milk Curd (Dahi)',
      category: 'Dairy',
      calories: 98,
      proteinGrams: 5.2,
      carbsGrams: 6.0,
      fatGrams: 6.0,
      glycemicIndex: 28.0,
      satietyIndex: 72.0,
    ),
    IndianFoodItem(
      id: 'khich_1',
      name: 'Moong Dal Khichdi',
      category: 'Comfort',
      calories: 210,
      proteinGrams: 7.2,
      carbsGrams: 38.0,
      fatGrams: 3.0,
      glycemicIndex: 55.0,
      satietyIndex: 72.0,
    ),
    IndianFoodItem(
      id: 'upma_1',
      name: 'Semolina Upma',
      category: 'Breakfast',
      calories: 190,
      proteinGrams: 4.0,
      carbsGrams: 34.0,
      fatGrams: 3.5,
      glycemicIndex: 65.0,
      satietyIndex: 62.0,
    ),
    IndianFoodItem(
      id: 'egg_1',
      name: 'Boiled Egg',
      category: 'High Protein',
      calories: 78,
      proteinGrams: 6.3,
      carbsGrams: 0.6,
      fatGrams: 5.3,
      glycemicIndex: 0.0,
      satietyIndex: 85.0,
    ),
  ];
}
