// lib/core/health_os/decision_hierarchy.dart
// §P0-E Health OS Brain — Decision Hierarchy
// Resolves conflicts between competing module guidance using a strict priority ladder.

/// The severity of a detected health or medical risk.
enum RiskSeverity { low, medium, high }

/// A health risk alert generated by the rule engine or predictive models.
class HealthRiskAlert {
  const HealthRiskAlert({
    required this.message,
    required this.severity,
    this.category = 'general',
  });

  final String message;
  final RiskSeverity severity;
  final String category;
}

/// Readiness score (0–100). Drives rest-day decisions.
class ReadinessScore {
  const ReadinessScore({required this.score, this.note});
  final int score;
  final String? note;
}

/// A structured training instruction from the user's active program.
class ProgramInstruction {
  const ProgramInstruction({
    required this.workoutType,
    required this.intensityLabel,
    required this.volumeDescription,
  });

  final String workoutType;
  final String intensityLabel;
  final String volumeDescription;

  TodaysPlan adaptedFor(UserGoals goals, UserPreferences prefs) {
    return TodaysPlan(
      planType: PlanType.program,
      workoutType: workoutType,
      intensityLabel: intensityLabel,
      volumeDescription: volumeDescription,
      message: 'Following your $workoutType session as scheduled.',
    );
  }
}

class UserGoals {
  const UserGoals({required this.primaryGoal, this.targetWeightKg});
  final String primaryGoal;
  final double? targetWeightKg;
}

class UserPreferences {
  const UserPreferences({
    this.preferredTone = 'motivational',
    this.vegetarian = false,
    this.prefersMorningWorkout = true,
  });
  final String preferredTone;
  final bool vegetarian;
  final bool prefersMorningWorkout;
}

/// The type of plan resolved for today.
enum PlanType { medicalRest, recoveryDay, program, goalDriven }

/// The fully resolved daily plan after conflict resolution.
class TodaysPlan {
  const TodaysPlan({
    required this.planType,
    required this.message,
    this.workoutType,
    this.intensityLabel,
    this.volumeDescription,
  });

  final PlanType planType;
  final String message;
  final String? workoutType;
  final String? intensityLabel;
  final String? volumeDescription;

  /// Creates a medical rest plan that overrides everything else.
  factory TodaysPlan.medicalRest({required String reason}) {
    return TodaysPlan(
      planType: PlanType.medicalRest,
      message: '⚠️ $reason Rest today. Consult your doctor before resuming.',
      workoutType: 'Rest',
      intensityLabel: 'None',
      volumeDescription: 'No training today.',
    );
  }

  /// Creates a recovery day plan when readiness drops critically low.
  factory TodaysPlan.recoveryDay({required String message}) {
    return TodaysPlan(
      planType: PlanType.recoveryDay,
      message: message,
      workoutType: 'Active Recovery',
      intensityLabel: 'Zone 1–2',
      volumeDescription: 'Light walk, stretching, or yoga only.',
    );
  }
}

/// §P0-E Decision Hierarchy — resolves conflicting module guidance.
///
/// Priority ladder (highest → lowest):
///   1. Medical Risk   — always overrides everything
///   2. Recovery State — readiness < 45 → forced rest day
///   3. Program Instruction — active structured training phase
///   4. Goals — user-stated outcomes
///   5. Preferences — tone, food type, schedule
class DecisionHierarchy {
  const DecisionHierarchy();

  /// Resolves today's plan from competing signals.
  TodaysPlan resolve({
    required HealthRiskAlert? medicalRisk,
    required ReadinessScore readiness,
    required ProgramInstruction programInstruction,
    required UserGoals goals,
    required UserPreferences preferences,
  }) {
    // Priority 1 — Medical Risk (always overrides everything)
    if (medicalRisk != null && medicalRisk.severity == RiskSeverity.high) {
      return TodaysPlan.medicalRest(reason: medicalRisk.message);
    }

    // Priority 2 — Recovery State (readiness < 45 → rest, no exceptions)
    if (readiness.score < 45) {
      return TodaysPlan.recoveryDay(
        message: 'Your readiness is critically low (${readiness.score}/100). '
            'Rest today protects your long-term progress.',
      );
    }

    // Priority 3 — Program Instruction (structured training phase)
    // If readiness is low but not critical (45–65), reduce intensity
    if (readiness.score < 65) {
      return TodaysPlan(
        planType: PlanType.program,
        workoutType: programInstruction.workoutType,
        intensityLabel: 'Zone 2 (reduced)',
        volumeDescription: 'Cut volume by 30% — readiness is sub-optimal.',
        message: 'Training today at reduced intensity. '
            'Readiness ${readiness.score}/100 — prioritize recovery tonight.',
      );
    }

    // Priority 4 & 5 — Goals + Preferences adapt the program instruction
    return programInstruction.adaptedFor(goals, preferences);
  }
}
