// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';
import 'package:drift/internal/migrations.dart';

class GeneratedHelper implements SchemaInstantiationHelper {
  @override
  GeneratedDatabase databaseForVersion(QueryExecutor db, int version) {
    switch (version) {
      case 9:
        return AppDatabaseAtV9(db);
      default:
        throw MissingSchemaException(version, versions);
    }
  }

  static const versions = const <int>[9];
}

class AppDatabaseAtV9 extends GeneratedDatabase {
  AppDatabaseAtV9(QueryExecutor db) : super(db);

  @override
  int get schemaVersion => 9;

  @override
  Iterable<TableInfo> get allTables => const [];
}
