import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../providers/food/food_bloc.dart';
import '../../providers/auth/auth_bloc.dart';
import '../../../core/constants/app_colors.dart';
import '../../../domain/entities/food_log_entity.dart';

class FoodSearchScreen extends StatefulWidget {
  const FoodSearchScreen({super.key});

  @override
  State<FoodSearchScreen> createState() => _FoodSearchScreenState();
}

class _FoodSearchScreenState extends State<FoodSearchScreen> {
  final _searchController = TextEditingController();

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final user = (context.read<AuthBloc>().state as Authenticated).user;

    return Scaffold(
      appBar: AppBar(title: const Text('Log Food')),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: TextField(
              controller: _searchController,
              decoration: InputDecoration(
                hintText: 'Search food (e.g. Banana, Oats)...',
                suffixIcon: IconButton(
                  icon: const Icon(Icons.search),
                  onPressed: () {
                    if (_searchController.text.isNotEmpty) {
                      context.read<FoodBloc>().add(
                        SearchFoodRequested(_searchController.text),
                      );
                    }
                  },
                ),
                border: const OutlineInputBorder(),
              ),
              onSubmitted: (value) {
                if (value.isNotEmpty) {
                  context.read<FoodBloc>().add(SearchFoodRequested(value));
                }
              },
            ),
          ),
          Expanded(
            child: BlocBuilder<FoodBloc, FoodState>(
              builder: (context, state) {
                if (state is FoodLoading) {
                  return const Center(child: CircularProgressIndicator());
                } else if (state is FoodSearchSuccess) {
                  return ListView.builder(
                    itemCount: state.results.length,
                    itemBuilder: (context, index) {
                      final food = state.results[index];
                      return ListTile(
                        title: Text(food.itemName),
                        subtitle: Text(
                          '${food.calories.toStringAsFixed(1)} kcal / 100g',
                        ),
                        trailing: IconButton(
                          icon: const Icon(
                            Icons.add_circle,
                            color: AppColors.saffron,
                          ),
                          onPressed: () {
                            // Create a new log entity with user ID and current date
                            final log = FoodLogEntity(
                              id: '', // Will be generated by PocketBase
                              userId: user.id,
                              itemName: food.itemName,
                              calories: food.calories,
                              macros: food.macros,
                              date: DateTime.now(),
                            );
                            context.read<FoodBloc>().add(LogFoodRequested(log));
                            ScaffoldMessenger.of(context).showSnackBar(
                              SnackBar(
                                content: Text('Logged ${food.itemName}'),
                              ),
                            );
                          },
                        ),
                      );
                    },
                  );
                } else if (state is FoodError) {
                  return Center(child: Text(state.message));
                }
                return const Center(
                  child: Text('Search for food to see results'),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}
