import '../models/nutrition_models.dart';

class IndianNutritionEngine {
  const IndianNutritionEngine();

  /// Comprehensive Seed Database of Indian Foods & Regional Staples
  static const List<FoodItem> seededIndianFoods = [
    // Grains & Breads
    FoodItem(
      id: 'food_roti_wheat',
      name: 'Whole Wheat Roti (Phulka)',
      nameHindi: 'गेहूं की रोटी (फुल्का)',
      region: IndianRegion.north,
      dietaryType: DietaryPreference.vegan,
      servingSizeGrams: 40,
      standardPortionUnit: '1 Roti',
      caloriesKcal: 85,
      proteinGrams: 3.1,
      carbsGrams: 17.5,
      fatGrams: 0.4,
      fiberGrams: 2.8,
      glycemicIndex: 62,
      ironMg: 1.2,
      calciumMg: 14.0,
    ),
    FoodItem(
      id: 'food_roti_jowar',
      name: 'Jowar Bhakri (Sorghum)',
      nameHindi: 'ज्वार की भाकरी',
      region: IndianRegion.west,
      dietaryType: DietaryPreference.vegan,
      servingSizeGrams: 50,
      standardPortionUnit: '1 Bhakri',
      caloriesKcal: 110,
      proteinGrams: 3.8,
      carbsGrams: 22.0,
      fatGrams: 0.9,
      fiberGrams: 4.5,
      glycemicIndex: 49,
      ironMg: 1.8,
      calciumMg: 25.0,
    ),
    FoodItem(
      id: 'food_roti_ragi',
      name: 'Ragi Roti / Mudde (Finger Millet)',
      nameHindi: 'रागी की रोटी / मुड्डे',
      region: IndianRegion.south,
      dietaryType: DietaryPreference.vegan,
      servingSizeGrams: 50,
      standardPortionUnit: '1 Roti',
      caloriesKcal: 115,
      proteinGrams: 3.5,
      carbsGrams: 24.0,
      fatGrams: 0.7,
      fiberGrams: 5.2,
      glycemicIndex: 44,
      calciumMg: 160.0,
      ironMg: 2.1,
    ),
    FoodItem(
      id: 'food_rice_white_cooked',
      name: 'Steamed White Rice (Basmati/Sona Masoori)',
      nameHindi: 'पका हुआ सफेद चावल',
      region: IndianRegion.panIndia,
      dietaryType: DietaryPreference.vegan,
      servingSizeGrams: 150,
      standardPortionUnit: '1 Katori (Medium)',
      caloriesKcal: 195,
      proteinGrams: 4.0,
      carbsGrams: 44.0,
      fatGrams: 0.5,
      fiberGrams: 0.8,
      glycemicIndex: 73,
    ),
    FoodItem(
      id: 'food_rice_brown_cooked',
      name: 'Cooked Brown Rice',
      nameHindi: 'भूरा चावल',
      region: IndianRegion.panIndia,
      dietaryType: DietaryPreference.vegan,
      servingSizeGrams: 150,
      standardPortionUnit: '1 Katori (Medium)',
      caloriesKcal: 165,
      proteinGrams: 3.8,
      carbsGrams: 35.0,
      fatGrams: 1.4,
      fiberGrams: 2.8,
      glycemicIndex: 55,
      ironMg: 0.8,
    ),

    // Dals & Curries
    FoodItem(
      id: 'food_dal_yellow_tadka',
      name: 'Yellow Moong Dal Tadka',
      nameHindi: 'पीली मूंग दाल तड़का',
      region: IndianRegion.panIndia,
      dietaryType: DietaryPreference.vegetarian,
      servingSizeGrams: 150,
      standardPortionUnit: '1 Katori',
      caloriesKcal: 140,
      proteinGrams: 8.5,
      carbsGrams: 19.0,
      fatGrams: 3.5,
      fiberGrams: 4.2,
      glycemicIndex: 38,
      ironMg: 2.4,
      calciumMg: 35.0,
    ),
    FoodItem(
      id: 'food_chole_masala',
      name: 'Punjabi Chole (Chickpeas Curry)',
      nameHindi: 'पंजाबी छोले',
      region: IndianRegion.north,
      dietaryType: DietaryPreference.vegetarian,
      servingSizeGrams: 150,
      standardPortionUnit: '1 Katori',
      caloriesKcal: 210,
      proteinGrams: 10.2,
      carbsGrams: 28.0,
      fatGrams: 6.5,
      fiberGrams: 6.8,
      glycemicIndex: 35,
      ironMg: 3.1,
      calciumMg: 45.0,
    ),
    FoodItem(
      id: 'food_rajma_curry',
      name: 'Rajma Masala (Kidney Beans)',
      nameHindi: 'राजमा मसाला',
      region: IndianRegion.north,
      dietaryType: DietaryPreference.vegetarian,
      servingSizeGrams: 150,
      standardPortionUnit: '1 Katori',
      caloriesKcal: 180,
      proteinGrams: 9.8,
      carbsGrams: 26.0,
      fatGrams: 4.2,
      fiberGrams: 7.1,
      glycemicIndex: 34,
      ironMg: 2.9,
    ),
    FoodItem(
      id: 'food_sambar',
      name: 'South Indian Sambar (Drumstick & Veg)',
      nameHindi: 'सांभर (दाल व सब्जियां)',
      region: IndianRegion.south,
      dietaryType: DietaryPreference.vegan,
      servingSizeGrams: 150,
      standardPortionUnit: '1 Katori',
      caloriesKcal: 95,
      proteinGrams: 4.5,
      carbsGrams: 14.0,
      fatGrams: 2.2,
      fiberGrams: 3.8,
      glycemicIndex: 40,
      ironMg: 1.5,
      calciumMg: 40.0,
    ),

    // Dairy & Proteins
    FoodItem(
      id: 'food_paneer_raw',
      name: 'Fresh Cow Milk Paneer',
      nameHindi: 'ताज़ा पनीर',
      region: IndianRegion.panIndia,
      dietaryType: DietaryPreference.vegetarian,
      servingSizeGrams: 100,
      standardPortionUnit: '100g (Approx 6 cubes)',
      caloriesKcal: 265,
      proteinGrams: 18.3,
      carbsGrams: 3.5,
      fatGrams: 20.0,
      fiberGrams: 0.0,
      glycemicIndex: 10,
      calciumMg: 480.0,
      vitaminB12Mcg: 1.1,
    ),
    FoodItem(
      id: 'food_curd_dahi',
      name: 'Fresh Set Curd (Dahi)',
      nameHindi: 'घर का जमा दही',
      region: IndianRegion.panIndia,
      dietaryType: DietaryPreference.vegetarian,
      servingSizeGrams: 150,
      standardPortionUnit: '1 Katori',
      caloriesKcal: 98,
      proteinGrams: 5.2,
      carbsGrams: 6.8,
      fatGrams: 5.0,
      fiberGrams: 0.0,
      glycemicIndex: 28,
      calciumMg: 180.0,
      vitaminB12Mcg: 0.6,
    ),
    FoodItem(
      id: 'food_egg_boiled',
      name: 'Whole Boiled Egg',
      nameHindi: 'उबला हुआ अंडा',
      region: IndianRegion.panIndia,
      dietaryType: DietaryPreference.eggetarian,
      servingSizeGrams: 50,
      standardPortionUnit: '1 Whole Egg',
      caloriesKcal: 74,
      proteinGrams: 6.3,
      carbsGrams: 0.4,
      fatGrams: 5.1,
      fiberGrams: 0.0,
      glycemicIndex: 0,
      vitaminB12Mcg: 0.9,
    ),
    FoodItem(
      id: 'food_chicken_curry_home',
      name: 'Home-style Chicken Curry (Lean Breast)',
      nameHindi: 'घरेलू चिकन करी',
      region: IndianRegion.panIndia,
      dietaryType: DietaryPreference.nonVegetarian,
      servingSizeGrams: 150,
      standardPortionUnit: '1 Katori (2-3 pieces)',
      caloriesKcal: 220,
      proteinGrams: 24.5,
      carbsGrams: 4.5,
      fatGrams: 11.0,
      fiberGrams: 1.2,
      glycemicIndex: 12,
      vitaminB12Mcg: 1.4,
      ironMg: 1.6,
    ),

    // Breakfast & South Indian Staples
    FoodItem(
      id: 'food_idli_steamed',
      name: 'Steamed Rice & Urad Dal Idli',
      nameHindi: 'इडली (भाप में पकी)',
      region: IndianRegion.south,
      dietaryType: DietaryPreference.vegan,
      servingSizeGrams: 60,
      standardPortionUnit: '2 Medium Idlis',
      caloriesKcal: 116,
      proteinGrams: 4.2,
      carbsGrams: 24.0,
      fatGrams: 0.4,
      fiberGrams: 1.6,
      glycemicIndex: 68,
    ),
    FoodItem(
      id: 'food_dosa_plain',
      name: 'Plain Crisp Dosa',
      nameHindi: 'सादा डोसा',
      region: IndianRegion.south,
      dietaryType: DietaryPreference.vegetarian,
      servingSizeGrams: 80,
      standardPortionUnit: '1 Dosa',
      caloriesKcal: 168,
      proteinGrams: 3.9,
      carbsGrams: 28.0,
      fatGrams: 4.5,
      fiberGrams: 1.4,
      glycemicIndex: 65,
    ),
    FoodItem(
      id: 'food_poha_veg',
      name: 'Vegetable Poha with Peanuts',
      nameHindi: 'सब्जी वाला पोहा (मूंगफली युक्त)',
      region: IndianRegion.west,
      dietaryType: DietaryPreference.vegan,
      servingSizeGrams: 150,
      standardPortionUnit: '1 Plate / Medium Bowl',
      caloriesKcal: 220,
      proteinGrams: 5.5,
      carbsGrams: 36.0,
      fatGrams: 6.8,
      fiberGrams: 3.4,
      glycemicIndex: 64,
      ironMg: 2.8,
    ),

    // Healthy Snacks & Street Foods
    FoodItem(
      id: 'food_makhana_roasted',
      name: 'Roasted Makhana (Foxnuts in Ghee)',
      nameHindi: 'भुना हुआ मखाना',
      region: IndianRegion.north,
      dietaryType: DietaryPreference.vegetarian,
      servingSizeGrams: 30,
      standardPortionUnit: '1 Big Bowl (30g)',
      caloriesKcal: 115,
      proteinGrams: 3.2,
      carbsGrams: 22.0,
      fatGrams: 1.8,
      fiberGrams: 2.9,
      glycemicIndex: 38,
      calciumMg: 36.0,
    ),
    FoodItem(
      id: 'food_samosa_fried',
      name: 'Deep Fried Potato Samosa',
      nameHindi: 'आलू समोसा (तला हुआ)',
      region: IndianRegion.north,
      dietaryType: DietaryPreference.vegan,
      servingSizeGrams: 90,
      standardPortionUnit: '1 Samosa',
      caloriesKcal: 260,
      proteinGrams: 4.1,
      carbsGrams: 32.0,
      fatGrams: 14.5,
      fiberGrams: 1.8,
      glycemicIndex: 78,
    ),
    FoodItem(
      id: 'food_chai_sugar',
      name: 'Indian Masala Chai with Full Cream Milk & Sugar',
      nameHindi: 'मसाला चाय (दूध व चीनी युक्त)',
      region: IndianRegion.panIndia,
      dietaryType: DietaryPreference.vegetarian,
      servingSizeGrams: 120,
      standardPortionUnit: '1 Cup (120ml)',
      caloriesKcal: 95,
      proteinGrams: 2.5,
      carbsGrams: 14.5,
      fatGrams: 3.2,
      fiberGrams: 0.0,
      glycemicIndex: 60,
    ),
  ];

  /// Find foods by keyword (case-insensitive English or Hindi)
  List<FoodItem> searchFoods(String query) {
    if (query.trim().isEmpty) return seededIndianFoods;
    final lower = query.toLowerCase().trim();
    return seededIndianFoods.where((food) {
      return food.name.toLowerCase().contains(lower) || food.nameHindi.contains(lower);
    }).toList();
  }

  /// Calculate composite macronutrient and glycemic load for a list of meal components
  LoggedMeal buildMealFromComponents({
    required String id,
    required String userId,
    required String name,
    required MealType mealType,
    required List<MealComponent> components,
    int qualityScore = 75,
    double visionConfidence = 1.0,
    String? photoUrl,
    DateTime? loggedAt,
  }) {
    double totalCals = 0;
    double totalProtein = 0;
    double totalCarbs = 0;
    double totalFat = 0;
    double totalFiber = 0;

    for (final c in components) {
      totalCals += c.totalCalories;
      totalProtein += c.totalProtein;
      totalCarbs += c.totalCarbs;
      totalFat += c.totalFat;
      totalFiber += c.totalFiber;
    }

    return LoggedMeal(
      id: id,
      userId: userId,
      name: name,
      mealType: mealType,
      components: components,
      caloriesKcal: double.parse(totalCals.toStringAsFixed(1)),
      proteinGrams: double.parse(totalProtein.toStringAsFixed(1)),
      carbsGrams: double.parse(totalCarbs.toStringAsFixed(1)),
      fatGrams: double.parse(totalFat.toStringAsFixed(1)),
      fiberGrams: double.parse(totalFiber.toStringAsFixed(1)),
      mealQualityScore: qualityScore,
      visionConfidence: visionConfidence,
      photoUrl: photoUrl,
      loggedAt: loggedAt ?? DateTime.now(),
    );
  }
}
