/// Readiness & Health Score Tier
enum ReadinessTier { basic, enhanced, premium }

/// §P4-A Live Metrics snapshot — loaded from Drift, no AI call
class DashboardLiveMetrics {
  final int steps;
  final int stepGoal;
  final int caloriesBurned;
  final int calorieGoal;
  final int activeMinutes;
  final int activeMinuteGoal;
  final double waterLitres;
  final double waterGoal;
  final double sleepHours;
  final int restingHrBpm;
  final int streakDays;
  final int karmaPoints;
  final double stepsVsYesterdayPct; // e.g. +12.0 = 12% more than yesterday

  const DashboardLiveMetrics({
    this.steps = 8420,
    this.stepGoal = 10000,
    this.caloriesBurned = 1240,
    this.calorieGoal = 1800,
    this.activeMinutes = 52,
    this.activeMinuteGoal = 60,
    this.waterLitres = 1.8,
    this.waterGoal = 3.0,
    this.sleepHours = 6.33, // 6h 20min
    this.restingHrBpm = 68,
    this.streakDays = 12,
    this.karmaPoints = 4280,
    this.stepsVsYesterdayPct = 12.0,
  });

  DashboardLiveMetrics copyWith({
    int? steps,
    int? stepGoal,
    int? caloriesBurned,
    int? calorieGoal,
    int? activeMinutes,
    int? activeMinuteGoal,
    double? waterLitres,
    double? waterGoal,
    double? sleepHours,
    int? restingHrBpm,
    int? streakDays,
    int? karmaPoints,
    double? stepsVsYesterdayPct,
  }) {
    return DashboardLiveMetrics(
      steps: steps ?? this.steps,
      stepGoal: stepGoal ?? this.stepGoal,
      caloriesBurned: caloriesBurned ?? this.caloriesBurned,
      calorieGoal: calorieGoal ?? this.calorieGoal,
      activeMinutes: activeMinutes ?? this.activeMinutes,
      activeMinuteGoal: activeMinuteGoal ?? this.activeMinuteGoal,
      waterLitres: waterLitres ?? this.waterLitres,
      waterGoal: waterGoal ?? this.waterGoal,
      sleepHours: sleepHours ?? this.sleepHours,
      restingHrBpm: restingHrBpm ?? this.restingHrBpm,
      streakDays: streakDays ?? this.streakDays,
      karmaPoints: karmaPoints ?? this.karmaPoints,
      stepsVsYesterdayPct: stepsVsYesterdayPct ?? this.stepsVsYesterdayPct,
    );
  }
}

/// §P4-A DIP — full schema used by Dashboard (DIP-only, zero AI calls on open)
class DailyIntelligencePackage {
  final String userId;
  final DateTime date;
  final int readinessScore; // 0–100
  final int healthScore; // 0–100
  final ReadinessTier readinessTier;
  final String primaryFocus;
  final String primaryInsight; // Pre-generated by Health OS Brain at 6am
  final String insightSource; // e.g. '7-day data · Sleep'
  final List<String> dailyMissions;
  final Map<String, dynamic> contextualMetadata;

  const DailyIntelligencePackage({
    required this.userId,
    required this.date,
    required this.readinessScore,
    this.healthScore = 74,
    required this.readinessTier,
    required this.primaryFocus,
    this.primaryInsight =
        'Your sleep debt is −45m. Prioritise 8h tonight to fully repair after yesterday\'s training load.',
    this.insightSource = '7-day data · Sleep',
    required this.dailyMissions,
    this.contextualMetadata = const {},
  });

  factory DailyIntelligencePackage.fromJson(Map<String, dynamic> json) {
    return DailyIntelligencePackage(
      userId: json['user_id'] as String,
      date: DateTime.parse(json['date'] as String),
      readinessScore: json['readiness_score'] as int,
      healthScore: json['health_score'] as int? ?? 74,
      readinessTier: ReadinessTier.values
          .byName(json['readiness_tier'] as String? ?? 'basic'),
      primaryFocus: json['primary_focus'] as String,
      primaryInsight: json['primary_insight'] as String? ?? '',
      insightSource: json['insight_source'] as String? ?? 'DIP',
      dailyMissions: List<String>.from(json['daily_missions'] ?? []),
      contextualMetadata:
          json['contextual_metadata'] as Map<String, dynamic>? ?? {},
    );
  }

  Map<String, dynamic> toJson() => {
        'user_id': userId,
        'date': date.toIso8601String(),
        'readiness_score': readinessScore,
        'health_score': healthScore,
        'readiness_tier': readinessTier.name,
        'primary_focus': primaryFocus,
        'primary_insight': primaryInsight,
        'insight_source': insightSource,
        'daily_missions': dailyMissions,
        'contextual_metadata': contextualMetadata,
      };
}
