enum RiskSeverity { low, moderate, high, critical }

/// Health Risk Alert generated by Preventive Intelligence Engine
class HealthRiskAlert {
  final String id;
  final String patternName;
  final String description;
  final RiskSeverity severity;
  final String recommendation;

  const HealthRiskAlert({
    required this.id,
    required this.patternName,
    required this.description,
    required this.severity,
    required this.recommendation,
  });
}

/// Rule-based Preventive Intelligence Engine evaluating all 6 risk patterns
class PreventiveIntelligenceEngine {
  const PreventiveIntelligenceEngine();

  /// Evaluate vitals history and return active risk alerts
  List<HealthRiskAlert> evaluateRiskPatterns({
    required double systolicBp,
    required double diastolicBp,
    required double fastingGlucoseMgDl,
    required double postprandialGlucoseMgDl,
    required double hrvDropRatio, // 3-day drop ratio vs 30-day baseline
    required double cumulativeSleepDeficitHours,
    required int consecutiveSedentaryDays,
    required int rhrSpikeBpm,
  }) {
    final alerts = <HealthRiskAlert>[];

    // Pattern 1: Hypertension Risk Pattern
    if (systolicBp > 135.0 || diastolicBp > 85.0) {
      alerts.add(HealthRiskAlert(
        id: 'p1_hypertension',
        patternName: 'Hypertension Risk Pattern',
        description: 'Elevated blood pressure (${systolicBp.round()}/${diastolicBp.round()} mmHg) detected.',
        severity: RiskSeverity.high,
        recommendation: 'Reduce sodium intake, avoid high-intensity max-effort lifts today.',
      ));
    }

    // Pattern 2: Glycemic Instability Pattern
    if (fastingGlucoseMgDl > 110.0 || postprandialGlucoseMgDl > 160.0) {
      alerts.add(HealthRiskAlert(
        id: 'p2_glycemic',
        patternName: 'Glycemic Instability Pattern',
        description: 'Postprandial/fasting glucose spike detected (${postprandialGlucoseMgDl.round()} mg/dL).',
        severity: RiskSeverity.moderate,
        recommendation: 'Opt for low glycemic-index complex carbs and take a 10min post-meal walk.',
      ));
    }

    // Pattern 3: Overtraining / HRV Collapse Pattern
    if (hrvDropRatio >= 0.25) {
      alerts.add(HealthRiskAlert(
        id: 'p3_hrv_collapse',
        patternName: 'Overtraining / HRV Collapse Pattern',
        description: '3-day consecutive HRV drop of ${(hrvDropRatio * 100).round()}% detected.',
        severity: RiskSeverity.high,
        recommendation: 'Mandatory active recovery day. Focus on sleep hygiene.',
      ));
    }

    // Pattern 4: Sleep Debt Accumulation Pattern
    if (cumulativeSleepDeficitHours >= 6.0) {
      alerts.add(HealthRiskAlert(
        id: 'p4_sleep_debt',
        patternName: 'Sleep Debt Accumulation Pattern',
        description: 'Cumulative sleep deficit of ${cumulativeSleepDeficitHours.toStringAsFixed(1)}h over rolling window.',
        severity: RiskSeverity.moderate,
        recommendation: 'Schedule a 20min power nap and advance bedtime by 45 minutes.',
      ));
    }

    // Pattern 5: Sedentary Stagnation Pattern
    if (consecutiveSedentaryDays >= 4) {
      alerts.add(HealthRiskAlert(
        id: 'p5_sedentary',
        patternName: 'Sedentary Stagnation Pattern',
        description: '< 3,500 steps logged for $consecutiveSedentaryDays consecutive days.',
        severity: RiskSeverity.low,
        recommendation: 'Break sedentary streak with a light 15-minute walking session.',
      ));
    }

    // Pattern 6: Cardiovascular Strain Spike Pattern
    if (rhrSpikeBpm >= 10) {
      alerts.add(HealthRiskAlert(
        id: 'p6_rhr_spike',
        patternName: 'Cardiovascular Strain Spike Pattern',
        description: 'Resting Heart Rate spiked by +$rhrSpikeBpm bpm above baseline.',
        severity: RiskSeverity.critical,
        recommendation: 'Monitor temperature and rest. Possible systemic fatigue or infection onset.',
      ));
    }

    return alerts;
  }
}
