enum RiskSeverity { low, moderate, high, critical }

/// Health Risk Alert generated by Preventive Intelligence Engine (§P4-F)
class HealthRiskAlert {
  final String id;
  final String patternName;
  final String description;
  final RiskSeverity severity;
  final String recommendation;
  final List<String> actions;

  const HealthRiskAlert({
    required this.id,
    required this.patternName,
    required this.description,
    required this.severity,
    required this.recommendation,
    this.actions = const [],
  });
}

/// User Health Trends enum for trend analysis
enum TrendDirection { rising, stable, declining }

/// Pure Dart Deterministic User Health Data Snapshot for §P4-F Trend Analysis
class UserHealthDataSnapshot {
  final TrendDirection bpTrend;
  final TrendDirection sleepTrend;
  final TrendDirection weightTrend;
  final TrendDirection stepsTrend;
  final TrendDirection glucoseTrend;
  final double bmi;
  final int stepAvg7d;
  final double systolicBp;
  final double diastolicBp;
  final double fastingGlucoseMgDl;
  final double postprandialGlucoseMgDl;
  final double hrvDropRatio; // 3-day drop ratio vs 30-day baseline
  final double cumulativeSleepDeficitHours;
  final int consecutiveSedentaryDays;
  final int rhrSpikeBpm;

  const UserHealthDataSnapshot({
    this.bpTrend = TrendDirection.stable,
    this.sleepTrend = TrendDirection.stable,
    this.weightTrend = TrendDirection.stable,
    this.stepsTrend = TrendDirection.stable,
    this.glucoseTrend = TrendDirection.stable,
    this.bmi = 24.0,
    this.stepAvg7d = 7500,
    this.systolicBp = 120.0,
    this.diastolicBp = 80.0,
    this.fastingGlucoseMgDl = 95.0,
    this.postprandialGlucoseMgDl = 120.0,
    this.hrvDropRatio = 0.05,
    this.cumulativeSleepDeficitHours = 1.0,
    this.consecutiveSedentaryDays = 0,
    this.rhrSpikeBpm = 0,
  });
}

/// Rule-based Preventive Intelligence Engine evaluating all 6 risk patterns (Deterministic — Zero AI)
class PreventiveIntelligenceEngine {
  const PreventiveIntelligenceEngine();

  /// Primary analysis method evaluating [UserHealthDataSnapshot] trends and metrics
  List<HealthRiskAlert> analyze(UserHealthDataSnapshot data) {
    final alerts = evaluateRiskPatterns(
      systolicBp: data.systolicBp,
      diastolicBp: data.diastolicBp,
      fastingGlucoseMgDl: data.fastingGlucoseMgDl,
      postprandialGlucoseMgDl: data.postprandialGlucoseMgDl,
      hrvDropRatio: data.hrvDropRatio,
      cumulativeSleepDeficitHours: data.cumulativeSleepDeficitHours,
      consecutiveSedentaryDays: data.consecutiveSedentaryDays,
      rhrSpikeBpm: data.rhrSpikeBpm,
    );

    // Multi-factor Trend Overrides per §P4-F / §P10-A specification:

    // 1. Hypertension Risk Pattern (BP rising + steps declining 7+ days)
    if ((data.bpTrend == TrendDirection.rising && data.stepsTrend == TrendDirection.declining) ||
        (data.bpTrend == TrendDirection.rising &&
            data.sleepTrend == TrendDirection.declining &&
            data.weightTrend == TrendDirection.rising &&
            data.stepsTrend == TrendDirection.declining)) {
      if (!alerts.any((a) => a.id == 'p1_hypertension')) {
        alerts.add(const HealthRiskAlert(
          id: 'p1_hypertension',
          patternName: 'Hypertension Risk Pattern',
          description: 'BP rising + declining steps detected.',
          severity: RiskSeverity.moderate,
          recommendation: 'Rising BP + declining steps is a hypertension risk pattern. Prioritize walking and sodium control.',
          actions: ['Log a 20-min walk', 'Reduce sodium', 'Check BP tomorrow'],
        ));
      }
    }

    // 2. Type 2 Diabetes Pattern (Glucose up + BMI >= 27)
    if ((data.glucoseTrend == TrendDirection.rising && data.bmi >= 27.0) ||
        (data.glucoseTrend == TrendDirection.rising && data.bmi >= 27.0 && data.stepAvg7d < 5000)) {
      if (!alerts.any((a) => a.id == 'p2_glycemic')) {
        alerts.add(const HealthRiskAlert(
          id: 'p2_glycemic',
          patternName: 'Type 2 Diabetes Pattern',
          description: 'Elevated glucose trend + high BMI.',
          severity: RiskSeverity.moderate,
          recommendation: 'Elevated glucose + high BMI detected. A 15-min post-meal walk reduces glucose spikes significantly.',
          actions: ['Walk after meals', 'Reduce refined carbs', 'Log fasting glucose'],
        ));
      }
    }

    // 3. Heart Disease Pattern (HR + BP elevated + poor sleep)
    if (data.rhrSpikeBpm >= 5 && (data.systolicBp > 130.0 || data.bpTrend == TrendDirection.rising) && data.sleepTrend == TrendDirection.declining) {
      if (!alerts.any((a) => a.id == 'p3_heart_disease')) {
        alerts.add(const HealthRiskAlert(
          id: 'p3_heart_disease',
          patternName: 'Heart Disease Prevention Risk',
          description: 'Elevated resting HR + elevated BP + poor sleep trend detected.',
          severity: RiskSeverity.high,
          recommendation: 'Cardiovascular stress detected. Prioritize sleep recovery and consult doctor if persistent.',
          actions: ['Prioritize 8h sleep', 'Avoid high caffeine', 'Schedule relaxation session'],
        ));
      }
    }

    // 4. Metabolic Syndrome Pattern (3+ risk factors present: high BP, high glucose, high BMI/waist)
    int metabolicRiskFactors = 0;
    if (data.systolicBp >= 130.0 || data.diastolicBp >= 85.0) metabolicRiskFactors++;
    if (data.fastingGlucoseMgDl >= 100.0 || data.glucoseTrend == TrendDirection.rising) metabolicRiskFactors++;
    if (data.bmi >= 27.0 || data.weightTrend == TrendDirection.rising) metabolicRiskFactors++;
    if (metabolicRiskFactors >= 3) {
      if (!alerts.any((a) => a.id == 'p4_metabolic_syndrome')) {
        alerts.add(const HealthRiskAlert(
          id: 'p4_metabolic_syndrome',
          patternName: 'Metabolic Syndrome Risk',
          description: '3+ metabolic risk factors present (BP, glucose, BMI).',
          severity: RiskSeverity.high,
          recommendation: 'Comprehensive lifestyle intervention required: daily 30-min walking + Satvik diet.',
          actions: ['30-min daily walk', 'Satvik diet swap', 'Biometric health review'],
        ));
      }
    }

    // 5. Burnout / Overtraining Pattern (HRV declining + HR elevated + performance dropping)
    if (data.hrvDropRatio >= 0.20 && data.rhrSpikeBpm >= 5 && data.sleepTrend == TrendDirection.declining) {
      if (!alerts.any((a) => a.id == 'p5_burnout')) {
        alerts.add(const HealthRiskAlert(
          id: 'p5_burnout',
          patternName: 'Burnout / Overtraining Risk',
          description: 'Declining HRV + elevated resting HR + sleep degradation detected.',
          severity: RiskSeverity.critical,
          recommendation: 'Immediate recovery protocol mandatory. Reduce training load by 50%.',
          actions: ['Deload training', '8h sleep target', 'Breathwork session'],
        ));
      }
    }

    // 6. Vitamin D Deficiency Pattern (Low outdoor steps + high fatigue 5+ days)
    if (data.stepAvg7d < 4000 && data.consecutiveSedentaryDays >= 5) {
      if (!alerts.any((a) => a.id == 'p6_vitamin_d')) {
        alerts.add(const HealthRiskAlert(
          id: 'p6_vitamin_d',
          patternName: 'Vitamin D Deficiency Risk',
          description: 'Low outdoor activity + sedentary stagnation 5+ days.',
          severity: RiskSeverity.low,
          recommendation: 'Get 15-20 mins of direct morning sunlight daily and check Vitamin D levels.',
          actions: ['15-min morning sunlight', 'Log outdoor walk', 'Vitamin D check'],
        ));
      }
    }

    return alerts;
  }

  /// Evaluate vitals history thresholds and return active risk alerts
  List<HealthRiskAlert> evaluateRiskPatterns({
    required double systolicBp,
    required double diastolicBp,
    required double fastingGlucoseMgDl,
    required double postprandialGlucoseMgDl,
    required double hrvDropRatio, // 3-day drop ratio vs 30-day baseline
    required double cumulativeSleepDeficitHours,
    required int consecutiveSedentaryDays,
    required int rhrSpikeBpm,
  }) {
    final alerts = <HealthRiskAlert>[];

    // Pattern 1: Hypertension Risk Pattern
    if (systolicBp > 135.0 || diastolicBp > 85.0) {
      alerts.add(HealthRiskAlert(
        id: 'p1_hypertension',
        patternName: 'Hypertension Risk Pattern',
        description: 'Elevated blood pressure (${systolicBp.round()}/${diastolicBp.round()} mmHg) detected.',
        severity: RiskSeverity.high,
        recommendation: 'Reduce sodium intake, avoid high-intensity max-effort lifts today.',
        actions: const ['Log a 20-min walk', 'Reduce sodium', 'Check BP tomorrow'],
      ));
    }

    // Pattern 2: Glycemic Instability / Diabetes Pattern
    if (fastingGlucoseMgDl > 110.0 || postprandialGlucoseMgDl > 160.0) {
      alerts.add(HealthRiskAlert(
        id: 'p2_glycemic',
        patternName: 'Glycemic Instability Pattern',
        description: 'Postprandial/fasting glucose spike detected (${postprandialGlucoseMgDl.round()} mg/dL).',
        severity: RiskSeverity.moderate,
        recommendation: 'Opt for low glycemic-index complex carbs and take a 10min post-meal walk.',
        actions: const ['Walk after meals', 'Reduce refined carbs', 'Log fasting glucose'],
      ));
    }

    // Pattern 3: Overtraining / HRV Collapse Pattern
    if (hrvDropRatio >= 0.25) {
      alerts.add(HealthRiskAlert(
        id: 'p3_hrv_collapse',
        patternName: 'Overtraining / HRV Collapse Pattern',
        description: '3-day consecutive HRV drop of ${(hrvDropRatio * 100).round()}% detected.',
        severity: RiskSeverity.high,
        recommendation: 'Mandatory active recovery day. Focus on sleep hygiene.',
        actions: const ['Schedule active recovery', 'Aim for 8h sleep', 'Hydrate with electrolytes'],
      ));
    }

    // Pattern 4: Sleep Debt Accumulation Pattern
    if (cumulativeSleepDeficitHours >= 6.0) {
      alerts.add(HealthRiskAlert(
        id: 'p4_sleep_debt',
        patternName: 'Sleep Debt Accumulation Pattern',
        description: 'Cumulative sleep deficit of ${cumulativeSleepDeficitHours.toStringAsFixed(1)}h over rolling window.',
        severity: RiskSeverity.moderate,
        recommendation: 'Schedule a 20min power nap and advance bedtime by 45 minutes.',
        actions: const ['Take 20min nap', 'Advance bedtime', 'Avoid late caffeine'],
      ));
    }

    // Pattern 5: Sedentary Stagnation Pattern
    if (consecutiveSedentaryDays >= 4) {
      alerts.add(HealthRiskAlert(
        id: 'p5_sedentary',
        patternName: 'Sedentary Stagnation Pattern',
        description: '< 3,500 steps logged for $consecutiveSedentaryDays consecutive days.',
        severity: RiskSeverity.low,
        recommendation: 'Break sedentary streak with a light 15-minute walking session.',
        actions: const ['Log 15-min walk', 'Perform desk stretches'],
      ));
    }

    // Pattern 6: Cardiovascular Strain Spike Pattern
    if (rhrSpikeBpm >= 10) {
      alerts.add(HealthRiskAlert(
        id: 'p6_rhr_spike',
        patternName: 'Cardiovascular Strain Spike Pattern',
        description: 'Resting Heart Rate spiked by +$rhrSpikeBpm bpm above baseline.',
        severity: RiskSeverity.critical,
        recommendation: 'Monitor temperature and rest. Possible systemic fatigue or infection onset.',
        actions: const ['Monitor temperature', 'Rest completely', 'Consult physician if symptomatic'],
      ));
    }

    return alerts;
  }
}
