/// §P5-F Grocery Optimization Engine 2.0
///
/// Pure-Dart meal plan ingredient aggregator, protein-per-rupee index,
/// knapsack heuristic budget optimizer, and protein substitute generator.
library;

// ─────────────────────────────────────────────────────────────────────────────
// Enums & Data Models
// ─────────────────────────────────────────────────────────────────────────────

/// Food categories for organizing grocery shopping lists.
enum GroceryCategory {
  protein,
  dairyAndEggs,
  grainsAndLegumes,
  produceAndVeggies,
  pantryAndOils,
}

/// Supported Quick-Commerce delivery partners (§P16-E integration).
enum VendorPartner { blinkit, zepto, swiggyInstamart }

/// A single grocery line item.
class GroceryItem {
  const GroceryItem({
    required this.id,
    required this.name,
    required this.quantityGrams,
    required this.unit,
    required this.priceInr,
    required this.proteinG,
    required this.category,
    this.isPurchased = false,
    this.isSwappedSubstitute = false,
    this.originalItemName,
  });

  final String id;
  final String name;
  final double quantityGrams;
  final String unit;
  final double priceInr;
  final double proteinG;
  final GroceryCategory category;
  final bool isPurchased;
  final bool isSwappedSubstitute;
  final String? originalItemName;

  /// Calculated cost in INR per gram of protein.
  double get costPerGramOfProtein {
    if (proteinG <= 0) return 0.0;
    return priceInr / proteinG;
  }

  GroceryItem copyWith({
    String? id,
    String? name,
    double? quantityGrams,
    String? unit,
    double? priceInr,
    double? proteinG,
    GroceryCategory? category,
    bool? isPurchased,
    bool? isSwappedSubstitute,
    String? originalItemName,
  }) {
    return GroceryItem(
      id: id ?? this.id,
      name: name ?? this.name,
      quantityGrams: quantityGrams ?? this.quantityGrams,
      unit: unit ?? this.unit,
      priceInr: priceInr ?? this.priceInr,
      proteinG: proteinG ?? this.proteinG,
      category: category ?? this.category,
      isPurchased: isPurchased ?? this.isPurchased,
      isSwappedSubstitute: isSwappedSubstitute ?? this.isSwappedSubstitute,
      originalItemName: originalItemName ?? this.originalItemName,
    );
  }
}

/// Result payload generated by [GroceryOptimizationEngine].
class OptimizedGroceryList {
  const OptimizedGroceryList({
    required this.items,
    required this.totalCostInr,
    required this.weeklyCostLimitInr,
    required this.monthlyBudgetInr,
    required this.isWithinBudget,
    required this.hasSwaps,
    required this.swapsAppliedCount,
    required this.totalSavedInr,
    this.budgetWarning,
  });

  final List<GroceryItem> items;
  final double totalCostInr;
  final double weeklyCostLimitInr;
  final double monthlyBudgetInr;
  final bool isWithinBudget;
  final bool hasSwaps;
  final int swapsAppliedCount;
  final double totalSavedInr;
  final String? budgetWarning;
}

// ─────────────────────────────────────────────────────────────────────────────
// Protein-per-Rupee Market Cost Index (§P5-F Specification)
// ─────────────────────────────────────────────────────────────────────────────

class ProteinCostIndex {
  ProteinCostIndex._();

  /// Benchmark INR per gram of protein for common Indian protein sources.
  static const Map<String, double> inrPerGramProtein = {
    'soya_chunks': 0.15,
    'eggs': 0.38,
    'double_toned_curd': 0.45,
    'black_chana': 0.60,
    'paneer': 0.75,
    'whey_protein': 1.10,
    'greek_yogurt': 1.50,
    'salmon': 2.40,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Grocery Optimization Engine Core
// ─────────────────────────────────────────────────────────────────────────────

class GroceryOptimizationEngine {
  const GroceryOptimizationEngine();

  /// Default baseline ingredients aggregated for a 7-day Indian high-protein plan.
  static List<GroceryItem> getSeedWeeklyIngredients() {
    return const [
      GroceryItem(
        id: 'ing_greek_yogurt',
        name: 'Greek Yogurt (Premium)',
        quantityGrams: 1400,
        unit: '7 tubs (200g)',
        priceInr: 560,
        proteinG: 70,
        category: GroceryCategory.protein,
      ),
      GroceryItem(
        id: 'ing_whey',
        name: 'Whey Protein Powder',
        quantityGrams: 210,
        unit: '7 scoops (30g)',
        priceInr: 315,
        proteinG: 168,
        category: GroceryCategory.protein,
      ),
      GroceryItem(
        id: 'ing_paneer',
        name: 'Fresh Cottage Cheese (Paneer)',
        quantityGrams: 1000,
        unit: '1 kg',
        priceInr: 320,
        proteinG: 180,
        category: GroceryCategory.dairyAndEggs,
      ),
      GroceryItem(
        id: 'ing_eggs',
        name: 'Farm Fresh Eggs',
        quantityGrams: 600,
        unit: '2 trays (24 eggs)',
        priceInr: 160,
        proteinG: 151,
        category: GroceryCategory.dairyAndEggs,
      ),
      GroceryItem(
        id: 'ing_atta',
        name: 'Whole Wheat Atta',
        quantityGrams: 5000,
        unit: '5 kg pack',
        priceInr: 240,
        proteinG: 120,
        category: GroceryCategory.grainsAndLegumes,
      ),
      GroceryItem(
        id: 'ing_dal',
        name: 'Yellow Toor & Moong Dal',
        quantityGrams: 2000,
        unit: '2 kg pack',
        priceInr: 280,
        proteinG: 240,
        category: GroceryCategory.grainsAndLegumes,
      ),
      GroceryItem(
        id: 'ing_veggies',
        name: 'Assorted Fresh Vegetables (Spinach, Tomatoes, Onions)',
        quantityGrams: 4000,
        unit: '4 kg basket',
        priceInr: 220,
        proteinG: 20,
        category: GroceryCategory.produceAndVeggies,
      ),
      GroceryItem(
        id: 'ing_oil',
        name: 'Cold Pressed Mustard & Coconut Oil',
        quantityGrams: 1000,
        unit: '1 Litre bottle',
        priceInr: 210,
        proteinG: 0,
        category: GroceryCategory.pantryAndOils,
      ),
    ];
  }

  /// Optimizes a weekly grocery list based on the user's monthly budget.
  /// Converts monthly budget to weekly cost limit (`monthlyBudgetInr / 4.33`).
  OptimizedGroceryList optimize({
    required List<GroceryItem> rawList,
    required double monthlyBudgetInr,
    required int dailyProteinTargetG,
  }) {
    final weeklyCostLimit = monthlyBudgetInr / 4.33;
    final initialCost = _calculateCost(rawList);

    if (initialCost <= weeklyCostLimit) {
      return OptimizedGroceryList(
        items: rawList,
        totalCostInr: double.parse(initialCost.toStringAsFixed(1)),
        weeklyCostLimitInr: double.parse(weeklyCostLimit.toStringAsFixed(1)),
        monthlyBudgetInr: monthlyBudgetInr,
        isWithinBudget: true,
        hasSwaps: false,
        swapsAppliedCount: 0,
        totalSavedInr: 0.0,
      );
    }

    // Heuristic protein-per-rupee optimization:
    // Sort items by costPerGramOfProtein descending, substitute expensive protein items (> ₹1.0 / g protein).
    final optimized = <GroceryItem>[];
    double accumulatedCost = 0.0;
    int swapsCount = 0;
    double initialProteinCostTotal = 0.0;
    double newProteinCostTotal = 0.0;

    for (final item in rawList) {
      if (item.category == GroceryCategory.protein &&
          item.costPerGramOfProtein > 1.0) {
        final substitute = _findCheaperProteinSubstitute(item);
        optimized.add(substitute);
        accumulatedCost += substitute.priceInr;
        swapsCount++;
        initialProteinCostTotal += item.priceInr;
        newProteinCostTotal += substitute.priceInr;
      } else {
        optimized.add(item);
        accumulatedCost += item.priceInr;
      }
    }

    final totalSaved = initialProteinCostTotal - newProteinCostTotal;
    final isBudgetMet = accumulatedCost <= weeklyCostLimit;

    final warning = !isBudgetMet
        ? 'Unable to meet target within ₹${monthlyBudgetInr.toInt()}/mo. Consider adjusting budget to ₹${(accumulatedCost * 4.33).round()}/mo.'
        : 'Swapped premium protein items to match ₹${monthlyBudgetInr.toInt()}/mo budget (Saved ~₹${totalSaved.round()}/wk).';

    return OptimizedGroceryList(
      items: optimized,
      totalCostInr: double.parse(accumulatedCost.toStringAsFixed(1)),
      weeklyCostLimitInr: double.parse(weeklyCostLimit.toStringAsFixed(1)),
      monthlyBudgetInr: monthlyBudgetInr,
      isWithinBudget: isBudgetMet,
      hasSwaps: swapsCount > 0,
      swapsAppliedCount: swapsCount,
      totalSavedInr: double.parse(totalSaved.toStringAsFixed(1)),
      budgetWarning: warning,
    );
  }

  /// Replaces expensive protein sources with high-yield budget options (Soya Chunks & Curd Mix).
  GroceryItem _findCheaperProteinSubstitute(GroceryItem expensiveItem) {
    // Example: Greek Yogurt (₹560 for 70g pro = ₹8.0/g) -> Soya Chunks & Double-Toned Curd (₹120 for 70g pro = ₹1.7/g)
    final substitutePrice = (expensiveItem.priceInr * 0.25).clamp(80.0, 180.0);
    return GroceryItem(
      id: '${expensiveItem.id}_sub',
      name: 'Soya Chunks & Double-Toned Curd Pack',
      quantityGrams: 1000,
      unit: '500g Soya + 1kg Curd',
      priceInr: substitutePrice,
      proteinG: expensiveItem.proteinG, // Preserves exact protein yield
      category: GroceryCategory.protein,
      isSwappedSubstitute: true,
      originalItemName: expensiveItem.name,
    );
  }

  double _calculateCost(List<GroceryItem> items) {
    return items.fold(0.0, (sum, item) => sum + item.priceInr);
  }
}
