/// §P5-H Protein Distribution & Timing Intelligence
///
/// Pure-Dart evaluator scoring daily protein distribution against the 25.0g
/// Muscle Protein Synthesis (MPS) threshold per main meal (Breakfast, Lunch, Dinner),
/// calculating 0–100 MPS timing scores, and generating actionable Indian timing nudges.
library;

import 'package:fitkarma/features/food/food_controller.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Domain Enums & Models
// ─────────────────────────────────────────────────────────────────────────────

/// Main meal types evaluated for Muscle Protein Synthesis (MPS).
enum MpsMealType { breakfast, lunch, dinner, snacks }

/// Result payload generated by [ProteinTimingEvaluator].
class ProteinTimingResult {
  const ProteinTimingResult({
    required this.score,
    required this.breakfastProteinG,
    required this.lunchProteinG,
    required this.dinnerProteinG,
    required this.snacksProteinG,
    required this.totalProteinG,
    required this.mealsMeetingMps,
    required this.mealsMissingMps,
    required this.timingNudge,
    required this.suggestedFoodAdditions,
  });

  /// 0.0 - 100.0 MPS distribution score.
  final double score;

  final double breakfastProteinG;
  final double lunchProteinG;
  final double dinnerProteinG;
  final double snacksProteinG;
  final double totalProteinG;

  final List<MpsMealType> mealsMeetingMps;
  final List<MpsMealType> mealsMissingMps;
  final String timingNudge;
  final List<String> suggestedFoodAdditions;
}

// ─────────────────────────────────────────────────────────────────────────────
// Protein Timing Evaluator
// ─────────────────────────────────────────────────────────────────────────────

class ProteinTimingEvaluator {
  const ProteinTimingEvaluator();

  /// Minimum protein threshold in grams per main meal to trigger optimal MPS.
  static const double mpsThresholdGrams = 25.0;

  /// Evaluates protein distribution across logged meals.
  ProteinTimingResult evaluateDistribution(List<FoodItem> loggedItems) {
    double breakfastPro = 0.0;
    double lunchPro = 0.0;
    double dinnerPro = 0.0;
    double snacksPro = 0.0;

    for (final item in loggedItems) {
      final type = _normalizeMealType(item.mealType);
      switch (type) {
        case MpsMealType.breakfast:
          breakfastPro += item.protein;
          break;
        case MpsMealType.lunch:
          lunchPro += item.protein;
          break;
        case MpsMealType.dinner:
          dinnerPro += item.protein;
          break;
        case MpsMealType.snacks:
          snacksPro += item.protein;
          break;
      }
    }

    final totalPro = breakfastPro + lunchPro + dinnerPro + snacksPro;
    final meetingMps = <MpsMealType>[];
    final missingMps = <MpsMealType>[];

    if (breakfastPro >= mpsThresholdGrams) {
      meetingMps.add(MpsMealType.breakfast);
    } else {
      missingMps.add(MpsMealType.breakfast);
    }

    if (lunchPro >= mpsThresholdGrams) {
      meetingMps.add(MpsMealType.lunch);
    } else {
      missingMps.add(MpsMealType.lunch);
    }

    if (dinnerPro >= mpsThresholdGrams) {
      meetingMps.add(MpsMealType.dinner);
    } else {
      missingMps.add(MpsMealType.dinner);
    }

    // 0 - 100 MPS Score calculation
    double score = 10.0;
    switch (meetingMps.length) {
      case 3:
        score = 100.0;
        break;
      case 2:
        score = 70.0;
        break;
      case 1:
        score = 40.0;
        break;
      case 0:
        score = loggedItems.isEmpty ? 0.0 : 10.0;
        break;
    }

    // Construct AI timing nudge and Indian high-protein food suggestions
    final nudge = _generateTimingNudge(
      score: score,
      totalPro: totalPro,
      breakfastPro: breakfastPro,
      lunchPro: lunchPro,
      dinnerPro: dinnerPro,
      missingMps: missingMps,
    );

    final suggestions = _generateSuggestions(missingMps);

    return ProteinTimingResult(
      score: score,
      breakfastProteinG: breakfastPro,
      lunchProteinG: lunchPro,
      dinnerProteinG: dinnerPro,
      snacksProteinG: snacksPro,
      totalProteinG: totalPro,
      mealsMeetingMps: meetingMps,
      mealsMissingMps: missingMps,
      timingNudge: nudge,
      suggestedFoodAdditions: suggestions,
    );
  }

  MpsMealType _normalizeMealType(String mealType) {
    final lower = mealType.trim().toLowerCase();
    if (lower.contains('breakfast')) return MpsMealType.breakfast;
    if (lower.contains('lunch')) return MpsMealType.lunch;
    if (lower.contains('dinner')) return MpsMealType.dinner;
    return MpsMealType.snacks;
  }

  String _generateTimingNudge({
    required double score,
    required double totalPro,
    required double breakfastPro,
    required double lunchPro,
    required double dinnerPro,
    required List<MpsMealType> missingMps,
  }) {
    if (score == 100.0) {
      return 'Excellent protein timing! All 3 main meals hit the 25g MPS threshold for optimal muscle protein synthesis.';
    }

    if (totalPro <= 0) {
      return 'No protein logged yet today. Aim for at least 25g protein per main meal to trigger muscle recovery.';
    }

    // Identify highest density meal vs lowest density meal
    final mealMap = {
      'Breakfast': breakfastPro,
      'Lunch': lunchPro,
      'Dinner': dinnerPro,
    };

    String highestMeal = 'Dinner';
    double maxVal = dinnerPro;

    mealMap.forEach((key, val) {
      if (val > maxVal) {
        maxVal = val;
        highestMeal = key;
      }
    });

    final missingNames = missingMps.map((m) => _capitalise(m.name)).join(', ');

    if (maxVal > 45.0 && missingMps.isNotEmpty) {
      final shiftAmount = (maxVal - 30.0).round();
      final targetMeal = _capitalise(missingMps.first.name);
      return 'Your total protein is ${totalPro.round()}g, but ${maxVal.round()}g was eaten at $highestMeal while $missingNames had under 25g. We recommend moving ~$shiftAmount g of protein from $highestMeal to $targetMeal to optimize MPS.';
    }

    return 'Protein distribution is uneven ($missingNames below 25g MPS threshold). Shift protein sources evenly across Breakfast, Lunch, and Dinner for maximum recovery.';
  }

  List<String> _generateSuggestions(List<MpsMealType> missingMps) {
    final suggestions = <String>[];
    for (final meal in missingMps) {
      final mealName = _capitalise(meal.name);
      switch (meal) {
        case MpsMealType.breakfast:
          suggestions.add(
            'Add 3 Boiled Eggs or 1 glass Sattu Shake to $mealName (+18g to +20g pro)',
          );
          break;
        case MpsMealType.lunch:
          suggestions.add(
            'Add 100g Paneer Bhurji or Sprouted Moong to $mealName (+16g to +18g pro)',
          );
          break;
        case MpsMealType.dinner:
          suggestions.add(
            'Add 1 Bowl Yellow Dal / Soya Chunks to $mealName (+15g to +22g pro)',
          );
          break;
        case MpsMealType.snacks:
          suggestions.add(
            'Swap evening snack with Roasted Chana or Curd Bowl (+10g to +12g pro)',
          );
          break;
      }
    }
    return suggestions;
  }

  String _capitalise(String s) =>
      s.isEmpty ? s : s[0].toUpperCase() + s.substring(1);
}
