name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies & run code generation
        run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs

      - name: Build APK release
        run: |
          flutter build apk --debug \
            --dart-define=APPWRITE_ENDPOINT=${{ secrets.APPWRITE_ENDPOINT }} \
            --dart-define=APPWRITE_PROJECT_ID=${{ secrets.APPWRITE_PROJECT_ID }} \
            --dart-define=APPWRITE_DB_ID=fitkarma-db \
            --dart-define=REVENUECAT_API_KEY=${{ secrets.REVENUECAT_API_KEY }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 7
